#********START USER_INPUTS ********

TESTSIGMA_API_KEY=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI3Njc1NzE5MS1mNzBkLTQ5MTgtYWViYy0wYzdhMDk5OWRmMTMiLCJkb21haW4iOiJ0ZXN0c2lnbWF0ZWNoLmNvbSIsInRlbmFudElkIjoyODE3fQ.loijCwG1JTW11FPCtfvL2I9U4oIDlWCvQLmsg-4GDahpeto8wu4g2ghPX3_GxoK7MevYlqKYJt1sB1CvmmFUWg
TESTSIGMA_TEST_PLAN_ID=6440
MAX_WAIT_TIME_FOR_SCRIPT_TO_EXIT=180
REPORT_FILE_PATH=./junit-report.xml
RUNTIME_DATA_INPUT="buildurl=http://test.testsigma.com,data1=testdata"

#********END USER_INPUTS***********
